gcp_api_key: please_change_me
publish_url: https://qa-publish-teacher-training-courses.london.cloudapps.digital
find_url: https://qa-find-postgraduate-teacher-training.london.cloudapps.digital
bg_jobs:
  save_statistic:
    cron: "0 0 * * *" # daily at midnight
    class: "SaveStatisticJob"
    queue: save_statistic
environment:
  label: "qa"
  selector_name: "qa"
