name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: dfedigital/teacher-training-api

    steps:
    - name: Alert
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: twd_bat_devops
        SLACK_COLOR: '#ef5343'
        SLACK_ICON_EMOJI: ':github-logo:'
        SLACK_USERNAME: Teacher Training API
        SLACK_TITLE: This is a test alert
        SLACK_MESSAGE: '<@U0110MC89BJ> Please ignore'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
