name: Database Restore

on:
  push:
    branches:
      - db-restore-2

jobs:
  db_restore:
    name: Restore Database in ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [qa, staging]
    steps:
    - name: Setup cf cli 
      uses: DFE-Digital/bat-infrastructure/actions/setup-cf-cli@main
      with:
        CF_USERNAME:   ${{ secrets[format('CF_USERNAME_{0}', matrix.environment)] }}
        CF_PASSWORD:   ${{ secrets[format('CF_PASSWORD_{0}', matrix.environment)] }}
        CF_SPACE_NAME: bat-${{ matrix.environment }}
        INSTALL_CONDUIT: true

    - name: Install postgres client
      run: |
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)"-pgdg main | sudo tee  /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update && sudo apt-get install -y postgresql-client-11
        psql --version && pg_dump --version
        
    - name: Backup Azure DB
      run: pg_dump -E utf8 -c -v -w -d ${{ secrets.AZURE_DATABASE_NAME}} -f db_backup.sql
      env:
        PGHOST:     ${{ secrets[format('AZURE_DATABASE_HOST_{0}', matrix.environment)] }}
        PGUSER:     ${{ secrets[format('AZURE_DATABASE_USER_{0}', matrix.environment)] }}
        PGPASSWORD: ${{ secrets[format('AZURE_DATABASE_PASSWORD_{0}', matrix.environment)] }}

    - name: Restore database
      run: cf conduit ${POSTGRES_SERVICE_INSTANCE} -- psql < db_backup.sql
      env:
        POSTGRES_SERVICE_INSTANCE: teacher-training-api-postgres-${{ matrix.environment }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      if: ${{ always() }}
      with:
        name: db_backup_${{ matrix.environment }}
        path: db_backup.sql
        retention-days: 30
